import { Router } from 'express';
import type { Pool } from 'pg';
import { requireAuth, requireRole } from '../middleware/auth.js';
import { createPropertyController } from '../controllers/propertyController.js';
import { createUnitController } from '../controllers/unitController.js';
import { createTenancyController } from '../controllers/tenancyController.js';
import { createPaymentController } from '../controllers/paymentController.js';

export function createPortfolioRouter(database: Pool) {
  const router = Router();
  router.use(requireAuth(database), requireRole('OWNER', 'MANAGER'));
  const properties = createPropertyController(database);
  router.get('/properties', properties.list);
  router.get('/properties/summary', properties.summary);
  router.get('/properties/options', properties.options);
  router.get('/properties/:id', properties.get);
  router.post('/properties', properties.create);
  router.put('/properties/:id', properties.update);
  router.patch('/properties/:id/status', properties.status);
  const units = createUnitController(database);
  router.get('/units', units.list);
  router.get('/units/:id', units.get);
  router.post('/units', units.create);
  router.put('/units/:id', units.update);
  const tenancy = createTenancyController(database);
  router.get('/tenants', tenancy.tenants);
  router.post('/tenants', tenancy.createTenant);
  router.get('/tenants/:id', tenancy.tenant);
  router.put('/tenants/:id', tenancy.updateTenant);
  router.get('/leases', tenancy.leases);
  router.post('/leases', tenancy.create);
  router.get('/leases/options', tenancy.options);
  router.get('/leases/:id', tenancy.lease);
  router.put('/leases/:id', tenancy.update);
  router.post('/leases/:id/terminate', tenancy.terminate);
  const payments = createPaymentController(database);
  router.get('/payments', payments.list);
  router.post('/payments', payments.create);
  router.get('/payments/rent', payments.rent);
  router.get('/payments/options', payments.options);
  router.get('/payments/:id', payments.get);
  router.post('/payments/:id/void', payments.voidRecord);
  return router;
}
